# docker-compose.yml
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern-gamelist-backend
    restart: unless-stopped
    ports:
      - "5011:5011"
    environment:
      - PORT=5011
      - MONGO_URI=${MONGO_URI}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - VITE_API_URL=${http://192.168.1.51:5011}
    container_name: mern-gamelist-frontend
    restart: unless-stopped
    ports:
      - "8050:80"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
